name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Set up Python version
      #   uses: actions/setup-python@v3.0.0
      #   with:
      #     python-version: 3.8
      #     cache: "pip"

      - name: Install dependencies
        run: pip install pipenv && pipenv install

      - name: Build mkdocs
        run: pipenv run mkdocs build

      - name: Install firebase
        run: apt-get update && apt-get install npm -y && npm install -g firebase-tools

      - name: Deploy to Firebase
        env: # Or as an environment variable
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --token $FIREBASE_TOKEN
