name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install --upgrade pip && pip install pipenv && python --version ; pip --version ; pipenv --version; pipenv --python `which python`; pipenv install

      - name: Build mkdocs
        run: pipenv run mkdocs build

      - name: Deploy to Firebase
        uses: joinflux/firebase-tools@v9.16.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
